version: '3.9'


services:
  postgres:
    image: postgres:15
    container_name: chat-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ChatAppDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/val/lib/postgresql/data
        
volumes:
  pgdata: